cookie:
  expiry_days: 30
  key: aljferovrwbvrbt./r,b/ea,gbvte,hbr.
  name: refresh_token
credentials:
  usernames:
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: admin
      password: $2b$12$gI9tKEbYNKkE9arT96fGsuInELrhUG872yXZg1AskpeELoW25xQNy
    yhf:
      email: normanmises@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: yhf
      password: $2b$12$eUov136U7vD.MZ7.LEKQNOTS4ihWG0hfLoCcC6/HC31Lrm/7L97oW
    yhf123:
      email: yhf123@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: yhfyhf
      password: $2b$12$eKgr3rIb3UjTokabAi3pouTqVKvkQEYCCdQRyivkDetJXKi5Xeopu
    yhf233:
      email: yhf233@gmail.com
      logged_in: false
      name: yhfyhf
      password: $2b$12$BTVTWtOtxqlxbA83F5hWE.uj0lqwH5bb0z.Ezd23Prg2uLOZYM9Ki
    yhfyhfyhf:
      email: yhf@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: yhfyhfyhf
      password: $2b$12$LgC3CelG9zsuiMKTpvwTluhe/ugDV61s6d2i4kageGdNLhmeBpCtu
pre-authorized:
  emails: null
